# This is a basic workflow to help you get started with Actions

name: 自动构建 - Debug Build Channel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 解压 JSON
        uses: TonyBogdanov/zip@1.0
        with:
            args: unzip -qq -o ./json.jar -d ./

      - name: 解压 JLINE3
        uses: TonyBogdanov/zip@1.0
        with:
            args: unzip -qq -o ./jline3.jar -d ./

      - name: 解压 JANSI
        uses: TonyBogdanov/zip@1.0
        with:
            args: unzip -qq -o ./jansi.jar -d ./

      - name: 安装 JDK 17
        uses: actions/setup-java@v2
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'

      - name: 尝试编译项目
        run: |
            javac -d . -cp jansi.jar:jline3.jar:json.jar -encoding UTF-8 src/*.java src/console/*.java src/utils/*.java src/command/*.java src/plugins/*.java builtin-plugin/*.java
            echo "Manifest-Version: 1.0" > mf.txt
            echo "Main-Class: cn.xiaym.ndos.NDOSMain" >> mf.txt

      - name: 打包项目
        run: |
            cp builtin-plugin/plugin_meta ndosplugin/
            jar -cvmf mf.txt ndos.jar ./cn ./org ./ndosplugin

      - name: 上传 ndos.jar
        uses: actions/upload-artifact@v3
        with:
            name: debug-build
            path: ndos.jar
